amcl:
  ros__parameters:
    use_sim_time: true
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    initial_covariance_xx: 0.25
    initial_covariance_yy: 0.25
    initial_covariance_aa: 0.06

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    laser_frame_id: "lidar2d_0_laser"                #  frame réel du LIDAR
    scan_topic: "sensors/lidar2d_0/scan"             #  topic réel du LIDAR

    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false

    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 20.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"

    max_beams: 60
    max_particles: 3000
    min_particles: 500

    pf_err: 0.05
    pf_z: 0.99

    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1

    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.3

    tf_broadcast: true
    transform_tolerance: 2.0
    update_min_a: 0.1
    update_min_d: 0.15

    z_hit: 0.7
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/hiba/clearpath_ws/src/clearpath_nav2_demos/maps/warehouse.yaml"

map_saver:
  ros__parameters:
    use_sim_time: true
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: true

